# Generated by Django 6.0.7 on 2026-07-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic_core', '0012_remove_trackedsite_user_alter_pageview_page_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='page_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.CharField(max_length=100),
        ),
    ]
